name: release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - CGO_ENABLED=0
        binary: ghs
        goos:
          - windows
          - darwin
          - linux
          - freebsd
          - openbsd
          - netbsd
        goarch:
          - 386
          - amd64
          - arm
          - arm64
        ignore:
          - goos: freebsd
            goarch: arm
            goarm: 6
          - goos: openbsd
            goarch: arm
            goarm: 6
